### PR TITLE
fix: set configs from environment vars

### LINKED ISSUE #351: Prest docker connects to 127.0.0.1 instead of envrionment var
- pREST version (or commit ref): Latest docker image
- pREST endpoint: - 
- PostgreSQL version: latest postgres docker image
- Operating system: Ubuntu 18.04
- Go version: - 
- Log gist: - 

I have deployed prest in docker with the following command:
`sudo docker run -d \
-e PREST_HTTP_PORT=8092 \
-e PREST_PG_HOST=172.19.0.106 \
-e PREST_PG_USER=postgres \
-e PREST_PG_PASS=pass \
--name prod-prest \
--restart=always \
--net prod-network --ip 172.19.0.107 \
prest/prest `

But `sudo docker logs prod-prest` returns:
2019/04/18 14:59:33 [error] dial tcp 127.0.0.1:5432: connect: connection refused
2019/04/18 15:00:34 [msg] Using ./prest.toml config file.
2019/04/18 15:00:34 [error] dial tcp 127.0.0.1:5432: connect: connection refused
2019/04/18 15:01:36 [msg] Using ./prest.toml config file.
2019/04/18 15:01:36 [error] dial tcp 127.0.0.1:5432: connect: connection refused
2019/04/18 15:02:37 [msg] Using ./prest.toml config file.
2019/04/18 15:02:37 [error] dial tcp 127.0.0.1:5432: connect: connection refused

Why does prest try to connect to 127.0.0.1 instead of the specified envrionment variable?

Thanks!

### PR DESCRIPTION
**Pull request by tiaguinho**
Closes https://github.com/prest/prest/issues/351

### CODE REVIEW

**Comment by tiaguinho** [comment]
ping: @crgimenes @avelino

File: config.go [hunk 1]
```diff
@@ -198,6 +195,56 @@ func Load() {
 	}
 }
 
+func postgresFromEnv(cfg *Prest) (err error) {
+	// rewrite all pg config
+	if os.Getenv("PREST_PG_URL") != "" {
```
Comment (crgimenes) [inline config.go]: I believe it is better if you use the _LookupEnv_ function instead of calling _GetEnv_ twice for each variable.
https://golang.org/pkg/os/#example_LookupEnv

Comment (tiaguinho) [reply config.go]: Done

**Review by felipeweb — APPROVED** [review]
LGTM

**Review by crgimenes — APPROVED** [review]
LGTM
